name: unit test
on: push
jobs:
  build-test:
    env:
     BUILD_CONFIG: 'Release'
     SOLUTION: 'Solution1/UnitTest.sln'
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
            
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
         dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore $SOLUTION
      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG
      - name: Test with dotnet
        run: dotnet test $SOLUTION --configuration $BUILD_CONFIG --logger "trx;LogFileName=test-results.trx" || true
      
      - name: Publish Test result
        uses: dorny/test-reporter@v1
        if: always()
        with:
         name: DotNET tests
         path: "**/test-results.trx"
         reporter: dotnet-trx
         fail-on-error: true
